import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const rajdhani = Rajdhani({

  subsets:['latin'],
  weight:['300', '400', '500', '600', '700']

})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" className="h-full w-full overflow-hidden">
      <body
        className={` ${rajdhani.className} bg-bg h-full w-full overflow-x-hidden antialiased`}
      > 
        <NavBar/>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
