import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { SessionProvider } from "next-auth/react";
import Footer from "@/components/Footer";
import Toast from "@/components/Toast";
import { ToastProvider } from "@/contexts/ToastContext";

const rajdhani = Rajdhani({

  subsets:['latin'],
  weight:['300', '400', '500', '600', '700']

})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" className="h-full w-full overflow-hidden" suppressHydrationWarning>
      <body
        className={` ${rajdhani.className} bg-bg h-full w-full overflow-x-hidden antialiased`}
      >  
      
      <SessionProvider>
      <ToastProvider>
        <Toast />
        <NavBar/>
        {children}
        <Footer/>
      </ToastProvider>
      </SessionProvider>
      
      </body>
    </html>
  );
}
